# Generated by Django 3.1.6 on 2021-02-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=250)),
                ('evolution_level', models.IntegerField()),
                ('next_evolution', models.CharField(max_length=250)),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDENTITY.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('evolution_level', models.IntegerField()),
                ('next_evolution', models.CharField(max_length=250)),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDENTITY.pokemontype')),
            ],
        ),
    ]
